Reclamation/src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank]
    private ?\DateTimeInterface $date_d = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank]
    private ?\DateTimeInterface $date_f = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false, name: 'voiture', referencedColumnName: 'immatriculation')]
    #[Assert\NotBlank]
    private ?Voiture $voiture = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateD(): ?\DateTimeInterface
    {
        return $this->date_d;
    }

    public function setDateD(\DateTimeInterface $date_d): self
    {
        $this->date_d = $date_d;

        return $this;
    }

    public function getDateF(): ?\DateTimeInterface
    {
        return $this->date_f;
    }

    public function setDateF(\DateTimeInterface $date_f): self
    {
        $this->date_f = $date_f;

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): self
    {
        $this->voiture = $voiture;

        return $this;
    }
}

Reclamation/src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\Column(length: 20)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 20,
        minMessage: 'immatriculation must be at least {{ limit }} characters long',
        maxMessage: 'immatriculation cannot be longer than {{ limit }} characters',
    )]
    private ?string $immatriculation = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\PositiveOrZero]
    private ?int $kilometrage = null;

    #[ORM\Column(length: 30)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 30,
        minMessage: 'couleur must be at least {{ limit }} characters long',
        maxMessage: 'couleur cannot be longer than {{ limit }} characters',
    )]
    private ?string $couleur = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 255,
        minMessage: 'image url must be at least {{ limit }} characters long',
        maxMessage: 'image url cannot be longer than {{ limit }} characters',
    )]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'voitures')]
    #[ORM\JoinColumn(nullable: false, name: 'categorie', referencedColumnName: 'id')]
    #[Assert\NotBlank]
    private ?Category $categorie = null;

    #[ORM\OneToMany(mappedBy: 'voiture', targetEntity: Reservation::class, orphanRemoval: true)]
    private Collection $reservations;

    #[ORM\OneToMany(mappedBy: 'voiture', targetEntity: VoitureRate::class, orphanRemoval: true)]
    private Collection $voitureRates;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->voitureRates = new ArrayCollection();
    }

    public function getImmatriculation(): ?string
    {
        return $this->immatriculation;
    }

    public function setImmatriculation(string $immatriculation): self
    {
        $this->immatriculation = $immatriculation;

        return $this;
    }

    public function getKilometrage(): ?int
    {
        return $this->kilometrage;
    }

    public function setKilometrage(int $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?Category
    {
        return $this->categorie;
    }

    public function setCategorie(?Category $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setVoiture($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getVoiture() === $this) {
                $reservation->setVoiture(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->couleur . ' ' . $this->categorie . ' (' . $this->immatriculation . ')';
    }
}

Reclamation/src/Form/VoitureType.php
<?php

namespace App\Form;

use App\Entity\Voiture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoitureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('immatriculation')
            ->add('kilometrage')
            ->add('couleur')
            ->add('image')
            ->add('categorie')
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Voiture::class,
        ]);
    }
}

Reclamation/src/Controller/VoitureController.php
<?php

namespace App\Controller;

use App\Entity\Voiture; 
use App\Entity\Reservation;
use App\Entity\VoitureRate;
use App\Form\VoitureType;
use App\Form\RateVoitureType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/voiture')]
class VoitureController extends AbstractController
{
    #[Route('/', name: 'app_voiture_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {


        $query = "select v.immatriculation, c.marque, c.modele, v.kilometrage, v.couleur, v.image, sum(r.rating) as sum, count(r.voiture) as total from App\Entity\Category c, App\Entity\Voiture v left join App\Entity\VoitureRate r with v.immatriculation = r.voiture  where v.categorie = c.id group by v.immatriculation";
        $voitures = $entityManager
            ->createQuery($query)
            ->getResult();

        $voitures_count = count($voitures);
        $reservations_count = count($entityManager
            ->getRepository(Reservation::class)
            ->findAll());

        $query = "select count(v.immatriculation) as nb, c.marque, c.modele from App\Entity\Category c, App\Entity\Voiture v, App\Entity\Reservation r where v.categorie = c.id and v.immatriculation = r.voiture group by v.immatriculation order by nb desc";

        $top = $entityManager
            ->createQuery($query)
            ->getResult();

        if (count($top) > 0) {
            $top_reservation = $top[0]['marque'] . ' ' . $top[0]['modele'];
        } else {
            $top_reservation = "None";
        }

        return $this->render('voiture/index.html.twig', [
            'voitures' => $voitures,
            'voitures_count' => $voitures_count,
            'reservations_count' => $reservations_count,
            'top_reservation' => $top_reservation,
        ]);
    }
    
    #[Route('/new', name: 'app_voiture_create', methods: ['GET', 'POST'])]
    public function create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $voiture = new Voiture();
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // check if it is already in the database

            $does_voiture_exist = $entityManager
                ->getRepository(Voiture::class)
                ->findOneBy(['immatriculation' => $voiture->getImmatriculation()]);

            if ($does_voiture_exist) {
                $this->addFlash('error', 'Cette voiture existe déjà');
                return $this->renderForm('voiture/create-voiture.html.twig', [
                    'voiture' => $voiture,
                    'form' => $form,
                ]);
            }

            $entityManager->persist($voiture);
            $entityManager->flush();
            $this->addFlash('success', 'La voiture a été ajoutée avec succès');
            return $this->redirectToRoute('app_voiture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('voiture/create-voiture.html.twig', [
            'voiture' => $voiture,
            'form' => $form,
        ]);
    }


    #[Route('/rate/{id}', name: 'app_voiture_rate', methods: ['GET', 'POST'])]
    public function rate(Request $request, EntityManagerInterface $entityManager): Response
    {
        $rate = new VoitureRate(); 
        $id = $request->get('id');

        $voiture = $entityManager
            ->getRepository(Voiture::class)
            ->findOneBy(['immatriculation' => $id]);
            
        $rate->setVoiture($voiture);
        $form = $this->createForm(RateVoitureType::class, $rate);
        $form->handleRequest($request);

        $voiture = $entityManager
            ->getRepository(Voiture::class)
            ->findOneBy(['immatriculation' => $id]);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($rate);
            $entityManager->flush();
            $this->addFlash('success', 'Rating added successfully');
            return $this->redirectToRoute('app_voiture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('voiture/rate.html.twig', [
            'voiture' => $voiture,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_voiture_delete', methods: ['POST'])]
    public function delete(Request $request, Voiture $voiture, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voiture->getImmatriculation(), $request->request->get('_token'))) {
            
            echo $voiture;
            $entityManager->remove($voiture);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_voiture_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/edit/{id}', name: 'app_voiture_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Voiture $voiture, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_voiture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('voiture/edit-voiture.html.twig', [
            'voiture' => $voiture,
            'form' => $form,
        ]);
    }
}

Reclamation/templates/voiture/category.html.twig
{% extends 'base.voiture.html.twig' %}

{% block title %}
  Category
{% endblock %}

{% block stylesheets %}
  <style>
    input:invalid {
      border: 2px solid red;
    }
    
    .profile-card-4 {
      overflow: hidden;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0px 0px 25px rgba(0, 0, 0, 0.1);
      position: relative;
      margin: 10px auto;
      cursor: pointer;
    }
    
    .profile-card-4 img {
      max-width: 300px;
      height: 150px;
      object-fit: cover;
      transition: all 0.25s linear;
    }
    
    .profile-card-4 .profile-content {
      position: relative;
      padding: 15px;
      background-color: #fff;
    }
    
    .profile-card-4 .profile-name {
      font-weight: bold;
      font-size: 17px;
    }
    
    .profile-card-4 .profile-name p {
      font-weight: 600;
      font-size: 13px;
      letter-spacing: 1.5px;
    }
    
    .profile-card-4 .profile-description {
      color: #777;
      font-size: 12px;
      padding: 10px;
    }
    
    .profile-card-4 .profile-overview {
      padding: 15px 0px;
    }
    
    .profile-card-4 .profile-overview p {
      font-size: 10px;
      font-weight: 600;
      color: #777 !important;
    }
    
    .profile-card-4 .profile-overview h4 {
      color: #273751;
      font-weight: bold;
    }
    
    .profile-card-4 .profile-content::before {
      content: '';
      position: absolute;
      height: 20px;
      top: -10px;
      left: 0px;
      right: 0px;
      background-color: #fff;
      z-index: 0;
      transform: skewY(3deg);
    }
    
    .profile-card-4:hover img {
      transform: rotate(5deg) scale(1.1, 1.1);
      filter: brightness(110%);
    }
    
    .profile-card-2 {
      background-color: #fff;
      box-shadow: 0px 0px 25px rgba(0, 0, 0, 0.1);
      background-position: center;
      overflow: hidden;
      position: relative;
      margin: 10px auto;
      cursor: pointer;
      border-radius: 10px;
    }
    
    .profile-card-2 img {
      width: 500px;
      height: 200px;
      object-fit: cover;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-name {
      position: absolute;
      left: 30px;
      bottom: 70px;
      font-size: 30px;
      color: #fff;
      text-shadow: 0px 0px 20px rgba(0, 0, 0, 0.5);
      font-weight: bold;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-icons {
      position: absolute;
      bottom: 30px;
      right: 30px;
      color: #fff;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-username {
      position: absolute;
      bottom: 50px;
      left: 30px;
      color: #fff;
      font-size: 13px;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-icons .fa {
      margin: 5px;
    }
    
    .profile-card-2:hover img {
      filter: grayscale(100%);
    }
    
    .profile-card-2:hover .profile-name {
      bottom: 80px;
    }
    
    .profile-card-2:hover .profile-username {
      bottom: 60px;
    }
    
    .profile-card-2:hover .profile-icons {
      right: 40px;
      color: white;
    }
    
    .btn {
      color: white;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="hero-wrap">
    {% for message in app.flashes('success') %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-7 heading-section text-center">
          <h2 class="mb-4" style="padding-top: 121px;">Categories</h2>
        </div>
      </div>
      <div class="row justify-content-center" style="color: white;">
        <div class="container">
          <div class="row">
            {% for category in categories %}
              <div class="col-md-4">
                <div class="profile-card-2">
                  <img src="https://w0.peakpx.com/wallpaper/640/274/HD-wallpaper-black-car-black-dark-lights-nissan-race-speed.jpg" class="img img-responsive" />
                  <div class="profile-name">{{ category.modele }}
                    ({{ category.marque }})</div>
                  <div class="profile-username">@{{ category.id }}</div>
                  <div class="profile-icons">
                    <div style="width: 100%; display: flex; justify-content: center">
                      <a class="btn btn-info mr-4" href="{{ path('app_category_edit', { id: category.id }) }}">Update</a>
                      <form method="post" action="{{ path('app_category_delete', { id: category.id }) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}" />
                        <button class="btn btn-danger">Delete</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            {% else %}
              no records found
            {% endfor %}
            <div class="col-md-12" style="color: black; padding: 32px 0">
             <div class="heading-section text-center">
          <h2 class="mb-4" style="padding-top: 121px;">Create Categorie</h2>
        </div>
            {{ form_start(form, {'attr': {'class': 'contact-form'}}) }}
            <div class="row">
              <div class="col-md-6">
                {{ form_row(form.marque, {'attr': {'class': 'form-control', 'placeholder': 'Marque'}}) }}
              </div>
              <div class="col-md-6">
                {{ form_row(form.modele, {'attr': {'class': 'form-control', 'placeholder': 'Modele'}}) }}
              </div>

              <div class="col-md-12 text-center">
                <div class="form-group" style="margin-top: 17px;display: inline-block;">
                {{ form_row(form.submit, { 'label': 'Submit', 'attr': { 'class': 'btn btn-primary py-3 px-5' } }) }}
                </div>
              </div>
            </div>
          {{ form_end(form) }}
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Reclamation/templates/voiture/create-reservation-for-voiture.html.twig
{% extends 'base.voiture.html.twig' %}

{% block title %} Create Reservation {% endblock %}

{% block stylesheets %}
  <style>
     input:invalid {
     border: 2px solid red;
     }
    .hero-wrap {
      position: relative;
      background: url('https://img.freepik.com/premium-photo/abstract-blur-car-showroom-background_34836-261.jpg') center center no-repeat;
      background-size: cover;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="hero-wrap">

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}


    <div class="overlay"></div>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-7 heading-section text-center">
          <h2 class="mb-4" style="padding-top: 121px;">Create Reservation</h2>
        </div>
      </div>
      <div class="row justify-content-center" style="color: white;">
        <div class="col-md-8">
          {{ form_start(form, {'attr': {'class': 'contact-form'}}) }}
            <div class="row">
            <div class="col-md-6">
                <div>
                  <label for="reservation_voiture" class="required">
                    Voiture
                  </label>
                  <input type="text" id="reservation_voiture" name="voiture[voiture]" required="required" class="form-control" placeholder="Voiture" value="{{ id }}" disabled>
                </div>
              </div>
              <div class="col-md-6">
                {{ form_row(form.date_d, {'attr': {'class': 'form-control', 'placeholder': 'Date debut'}}) }}
              </div>
              <div class="col-md-6">
                {{ form_row(form.date_f, {'attr': {'class': 'form-control', 'placeholder': 'Date fin'}}) }}
              </div>
              <div class="col-md-12 text-center">
                <div class="form-group" style="margin-top: 17px;display: inline-block;">
                {{ form_row(form.submit, { 'label': 'Submit', 'attr': { 'class': 'btn btn-primary py-3 px-5' } }) }}
                </div>
              </div>
            </div>
          {{ form_end(form) }}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Reclamation/templates/voiture/edit-category.html.twig
{% extends 'base.voiture.html.twig' %}

{% block title %} Create Voiture {% endblock %}

{% block stylesheets %}
  <style>
     input:invalid {
     border: 2px solid red;
     }
    .hero-wrap {
      position: relative;
      background: url('https://img.freepik.com/premium-photo/abstract-blur-car-showroom-background_34836-261.jpg') center center no-repeat;
      background-size: cover;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="hero-wrap">
    

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}


    <div class="overlay"></div>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-7 heading-section text-center">
          <h2 class="mb-4" style="padding-top: 121px;">Update Category</h2>
        </div>
      </div>
      <div class="row justify-content-center" style="color: white;">
        <div class="col-md-8">

          {{ form_start(form, {'attr': {'class': 'contact-form'}}) }}
            <div class="row">
              <div class="col-md-6">
                {{ form_row(form.marque, {'attr': {'class': 'form-control', 'placeholder': 'Marque'}}) }}
              </div>
              <div class="col-md-6">
                {{ form_row(form.modele, {'attr': {'class': 'form-control', 'placeholder': 'Modele'}}) }}
              </div>
              <div class="col-md-12 text-center">
                <div class="form-group" style="margin-top: 17px;display: inline-block;">
                {{ form_row(form.submit, { 'label': 'Submit', 'attr': { 'class': 'btn btn-primary py-3 px-5' } }) }}
                </div>
              </div>
            </div>
          {{ form_end(form) }}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Reclamation/templates/voiture/reservations.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Reservations{% endblock %}

{% block body %}
            <ul class="nav flex-column " style="flex-direction: row !important" >
                 <li class="nav-item">
                    <a class="nav-link click-scroll" href="{{ path('app_voiture_index') }}">Voiture Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{{ path('app_category_index') }}">Categories</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{{ path('app_voiture_create') }}">Create Voiture</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{{ path('app_reservation_index') }}">Reservations</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{{ path('app_reservation_create') }}">Create Reservation</a>
                </li>

            </ul>

<div>
            <h3>Reservations List</h3>

        <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Voiture</th>
                <th>Date Debut</th>
                <th>Date Fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
               
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %} #}

{% extends 'base.voiture.html.twig' %}

{% block title %}
  Category
{% endblock %}

{% block stylesheets %}
  <style>
    input:invalid {
      border: 2px solid red;
    }
    
    .profile-card-4 {
      overflow: hidden;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0px 0px 25px rgba(0, 0, 0, 0.1);
      position: relative;
      margin: 10px auto;
      cursor: pointer;
    }
    
    .profile-card-4 img {
      max-width: 300px;
      height: 150px;
      object-fit: cover;
      transition: all 0.25s linear;
    }
    
    .profile-card-4 .profile-content {
      position: relative;
      padding: 15px;
      background-color: #fff;
    }
    
    .profile-card-4 .profile-name {
      font-weight: bold;
      font-size: 17px;
    }
    
    .profile-card-4 .profile-name p {
      font-weight: 600;
      font-size: 13px;
      letter-spacing: 1.5px;
    }
    
    .profile-card-4 .profile-description {
      color: #777;
      font-size: 12px;
      padding: 10px;
    }
    
    .profile-card-4 .profile-overview {
      padding: 15px 0px;
    }
    
    .profile-card-4 .profile-overview p {
      font-size: 10px;
      font-weight: 600;
      color: #777 !important;
    }
    
    .profile-card-4 .profile-overview h4 {
      color: #273751;
      font-weight: bold;
    }
    
    .profile-card-4 .profile-content::before {
      content: '';
      position: absolute;
      height: 20px;
      top: -10px;
      left: 0px;
      right: 0px;
      background-color: #fff;
      z-index: 0;
      transform: skewY(3deg);
    }
    
    .profile-card-4:hover img {
      transform: rotate(5deg) scale(1.1, 1.1);
      filter: brightness(110%);
    }
    
    .profile-card-2 {
      background-color: #fff;
      box-shadow: 0px 0px 25px rgba(0, 0, 0, 0.1);
      background-position: center;
      overflow: hidden;
      position: relative;
      margin: 10px auto;
      cursor: pointer;
      border-radius: 10px;
    }
    
    .profile-card-2 img {
      width: 500px;
      height: 300px;
      object-fit: cover;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-name {
      position: absolute;
      left: 30px;
      bottom: 120px;
      font-size: 30px;
      color: #fff;
      text-shadow: 0px 0px 20px rgba(0, 0, 0, 0.5);
      font-weight: bold;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-icons {
      position: absolute;
      bottom: 30px;
      right: 30px;
      color: #fff;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-username {
      position: absolute;
      bottom: 80px;
      left: 30px;
      color: #fff;
      font-size: 13px;
      transition: all linear 0.25s;
    }
    
    .profile-card-2 .profile-icons .fa {
      margin: 5px;
    }
    
    .profile-card-2:hover img {
      filter: grayscale(100%);
    }
    
    .profile-card-2:hover .profile-name {
      bottom: 80px;
    }
    
    .profile-card-2:hover .profile-username {
      bottom: 60px;
    }
    
    .profile-card-2:hover .profile-icons {
      right: 40px;
      color: white;
    }
    
    a {
      color: white;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="hero-wrap">
    {% for message in app.flashes('success') %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-7 heading-section text-center">
          <h2 class="mb-4" style="padding-top: 121px;">
            Reservations<div style="display: flex; justify-content: center; padding-bottom: 70px">
              <a class="btn btn-info" href="{{ path('app_reservation_create') }}">Create new Reservation</a>
            </div>
          </h2>
        </div>
      </div>
      <div class="row justify-content-center" style="color: white;">
        <div class="container">
          <div class="row">
            {% for reservation in reservations %}
              <div class="col-md-4">
                <div class="profile-card-2">
                  <img src="https://w0.peakpx.com/wallpaper/640/274/HD-wallpaper-black-car-black-dark-lights-nissan-race-speed.jpg" class="img img-responsive" />
                  <div class="profile-name" style="font-size: 17px; margin-top: 10px">{{ reservation.voiture }}</div>
                  <div class="profile-username">{{ reservation.dateD|date('m/d/Y') }} - {{ reservation.dateF|date('m/d/Y') }}</div>
                  <div class="profile-icons">
                    <div style="width: 100%; display: flex; justify-content: center">
                      <a class="btn btn-info mr-4" href="{{ path('app_reservation_edit', { id: reservation.id }) }}">Update</a>
                      <form method="post" action="{{ path('app_reservation_delete', { id: reservation.id }) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}" />
                        <button class="btn btn-danger">Delete</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            {% else %}
              no records found
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}